### ISSUE TITLE
WithoutEtcd does not actually drop etcd flags

### ISSUE THREAD

**Issue by raffis** [kubernetes-sigs/apiserver-runtime#78]
I would expect that if I build the command using `WithoutEtcd()` I will end up without any etcd related flags.
However this seems not to be the case. All etcd related cmd flags are still present.

A nasty workaround currently is to hide the flags before calling the `Execute()`.
```
rootCmd.Flags().MarkHidden("etcd-cafile")
rootCmd.Flags().MarkHidden("etcd-certfile")
rootCmd.Flags().MarkHidden("etcd-compaction-interval")
rootCmd.Flags().MarkHidden("etcd-count-metric-poll-period")
rootCmd.Flags().MarkHidden("etcd-db-metric-poll-interval")
rootCmd.Flags().MarkHidden("etcd-healthcheck-timeout")
rootCmd.Flags().MarkHidden("etcd-keyfile")
rootCmd.Flags().MarkHidden("etcd-prefix")
rootCmd.Flags().MarkHidden("etcd-servers")
rootCmd.Flags().MarkHidden("etcd-servers-overrides")
```

Also since the entire runtime depends on the internal sample-apiserver it makes it impossible to tweak these arguments in the first place, see issue #58.

**Comment by muff1nman** [comment]
Still valid

/remove-lifecycle rotten
