### ISSUE TITLE
Error: parent storageProvider for xxxxx must implement rest.StandardStorage

### ISSUE THREAD

**Issue by Jarvif** [kubernetes-sigs/apiserver-runtime#84]
Hi,everyboy.
    when i use the lastest version of the apiserver-runtime and controller-runtime. I can build the image successfully. But when i apply it in my cluster , it had a error : "Error: parent storageProvider for xxxxx must implement rest.StandardStorage". My project was right and can apply without mistake. But , now i want to update the lib of apiserver(newest include go.opentelemetry.io/otel v1.10.0 lib), it has the error. Can you help how to fix it ? 

   Thanks !
   Jarvif !

**Comment by Somefive** [comment]
Could you try to use the latest main branch and see if this issue still happens? The master branch has upgraded the k8s.io related repos to 0.26 which I think could be compatible with the latest controller-runtime as for the underlying otel dependencies.

**Comment by Jarvif** [comment]
已收到，谢谢。

**Comment by Jarvif** [comment]
I had used the latest main branch , thank.
