### ISSUE TITLE
k8s.io/apiserver v0.27.2 version not supported

### ISSUE THREAD

**Issue by free-hawk** [kubernetes-sigs/apiserver-runtime#93]
hi,kubernetes-sigs:
    In this release, storage has increased the SingularQualifiedResource.

k8s.io/apiserver/pkg/registry/generic/registry/store.go
<img width="944" alt="image" src="https://github.com/kubernetes-sigs/apiserver-runtime/assets/18590568/8d1c0785-f00e-4d6c-94f7-e193962ae181">
However, in the newStore method, no assignment is made to this field, resulting in an error when calling the store.CompleteWithOptions(options) method.

sigs.k8s.io/apiserver-runtime/pkg/builder/rest/rest.go
<img width="880" alt="image" src="https://github.com/kubernetes-sigs/apiserver-runtime/assets/18590568/dc48ed7e-d705-449f-9033-4244ae090c91">

error message: 
<img width="1689" alt="image" src="https://github.com/kubernetes-sigs/apiserver-runtime/assets/18590568/8ec8fe6f-9a43-45e2-9480-50415fe6c8b4">

**Comment by zengyuxing007** [comment]
ping @yue9944882
